[package]
name = "peggy"
version = "0.7.0"
edition = "2018"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]

[features]
default = []
runtime = []
peggygen = []
rustgen = ["quote"]

[dependencies]
quote = { version = "1.0.9", optional = true }
